### ISSUE TITLE
install of package 'rlang' failed 

### ISSUE THREAD

**Issue by lyashevska** [carpentries/actions#92]
In in `pr-receive.yaml` install of package 'rlang' fails.
Log can be seen [here](https://github.com/esciencecenter-digital-skills/git-lesson/actions/runs/9349999526/job/25733365456?pr=3).

Any help is appreciated.

**Comment by tobyhodges** [comment]
Please try configuring the automated pull requests to update the package dependencies on your lesson. You can find instructions with the results of the latest scheduled run of that workflow: https://github.com/esciencecenter-digital-skills/git-lesson/actions/runs/9359195190/attempts/1#summary-25762498266

After you have created that token and added it to the repository, open the _Actions_ tab and run the "03 Maintain: Update Package Cache" workflow. When it has finished running, that should open a pull request on your repository, which youc an merge to update the dependency versions.

[I did this on a copy of your lesson repository](https://github.com/tobyhodges/symmetrical-octo-memory/actions/runs/9363009404) and the lesson site is now building.

**Comment by lyashevska** [comment]
Thanks for your promt help @tobyhodges 
Just to confirm that this is working now.
